name: simple_dart_web_views
description: Simple dart web views.
version: 0.0.2
publish_to: none

environment:
  sdk: '^2.13.4'

dependencies:
  simple_dart_web_widgets:
    git: https://github.com/ViktorZahar/simple_dart_web_widgets.git

dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers:


