name: simple_dart_web_views
description: Simple dart web views.
version: 0.0.1
#homepage: https://www.example.com
#author: mi <email@example.com>

environment:
  sdk: '^2.0.0'

dependencies:
  simple_dart_web_widgets:
    path: ../simple_dart_web_widgets

dev_dependencies:
  build_runner:
  build_web_compilers:



web:
  compiler:
    debug: dartdevc
