name: simple_dart_web_views
description: Simple dart web views.
version: 0.0.1
publish_to: none

author: Viktor Zakharov  <viktorzahar@gmail.com>

environment:
  sdk: '^2.12.1'

dependencies:
  simple_dart_web_widgets:
      git: https://github.com/ViktorZahar/simple_dart_web_widgets.git

dev_dependencies:
  build_runner: ^1.12.1
  build_web_compilers: ^2.16.5


web:
  compiler:
    debug: dartdevc
